# Generated by Django 4.2.29 on 2026-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jvc_id', models.IntegerField(help_text='ID jeuxvideo.com', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jvc_id', models.IntegerField(help_text='ID jeuxvideo.com', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jvc_id', models.IntegerField(help_text='ID jeuxvideo.com', unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('game_type', models.IntegerField(choices=[(1, 'Série'), (2, 'Compilation'), (4, 'Masterfiche'), (9, 'Jeu'), (49, 'Fiche de jeu générique')], default=9)),
                ('release_date', models.CharField(blank=True, max_length=100)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='games', to='games.genre')),
                ('machines', models.ManyToManyField(blank=True, related_name='games', to='games.machine')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
