# Generated by Django 4.2.29 on 2026-03-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('amazon', 'Amazon')], default='amazon', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('product_url', models.URLField(blank=True, max_length=500)),
                ('product_title', models.CharField(blank=True, max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='games.game')),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['game', 'source', '-scraped_at'], name='games_price_game_id_44896a_idx')],
            },
        ),
    ]
