# Generated by Django 4.2.29 on 2026-03-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='asin',
            field=models.CharField(blank=True, help_text='Identifiant Amazon', max_length=20),
        ),
        migrations.AddField(
            model_name='price',
            name='availability',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='price',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='price',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='source',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('fnac', 'Fnac'), ('micromania', 'Micromania'), ('steam', 'Steam')], max_length=20),
        ),
    ]
