# Generated by Django 4.2.29 on 2026-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_price_asin_price_availability_price_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='source',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('galaxus', 'Galaxus'), ('fnac', 'Fnac'), ('micromania', 'Micromania'), ('steam', 'Steam')], max_length=20),
        ),
    ]
