# Generated by Django 4.2.29 on 2026-03-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_price_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='box_only_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Boîte seule', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='cib_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Complet en boîte', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='graded_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gradé WATA/VGA', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='manual_only_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manuel seul', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Neuf scellé', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='source',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('galaxus', 'Galaxus'), ('pricecharting', 'PriceCharting'), ('fnac', 'Fnac'), ('micromania', 'Micromania'), ('steam', 'Steam')], max_length=20),
        ),
    ]
