# Generated by Django 4.2.29 on 2026-03-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_price_box_only_price_price_cib_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ricardo', 'Ricardo'), ('ebay', 'eBay')], max_length=20)),
                ('platform_slug', models.SlugField(help_text='Console: snes, nes, n64, etc.', max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('listing_url', models.URLField(max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_now_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='CHF', max_length=3)),
                ('bid_count', models.IntegerField(default=0)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='games.game')),
            ],
            options={
                'ordering': ['ends_at'],
                'indexes': [models.Index(fields=['source', 'platform_slug'], name='games_listi_source_1f8d8a_idx'), models.Index(fields=['game', 'source'], name='games_listi_game_id_1e6074_idx')],
            },
        ),
    ]
