# Generated by Django 4.2.29 on 2026-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='source',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('galaxus', 'Galaxus'), ('pricecharting', 'PriceCharting'), ('ebay', 'eBay'), ('fnac', 'Fnac'), ('micromania', 'Micromania'), ('steam', 'Steam')], max_length=20),
        ),
    ]
