# Generated by Django 4.2.29 on 2026-03-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_price_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(blank=True, help_text='PAL, NTSC, JP', max_length=10),
        ),
    ]
