# Generated by Django 4.2.29 on 2026-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_listing_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='source',
            field=models.CharField(choices=[('ricardo', 'Ricardo'), ('ebay', 'eBay')], max_length=20),
        ),
    ]
